# Generated by Django 5.2.4 on 2025-07-25 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=50)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, help_text="weight in pounds", max_digits=5
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("image", models.ImageField(upload_to="cakes/")),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=20)),
                ("message", models.TextField(blank=True)),
                ("delivery_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cakes.cake"
                    ),
                ),
            ],
        ),
    ]
